change from r.get_info() to r.limits (#102)
I get 
> AttributeError: 'RateLimits' object has no attribute 'get_info'
But r.limits gives me the desired output.